### ISSUE TITLE
Connection lost due to NullPointerException immediately on receipt of first message

### ISSUE THREAD

**Issue by hjespers** [evokly/kafka-connect-mqtt#10]
Connector starts up up fine with Confluent Platform 3.0 but I get a java.lang.NullPointerException when I publish the first MQTT message using mosquitto broker and mosquito_pub. 

ERROR MQTT connection lost! (com.evokly.kafka.connect.mqtt.MqttSourceConnector:188)
MqttException (0) - java.lang.NullPointerException
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:176)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.evokly.kafka.connect.mqtt.util.Utils.getConfiguredInstance(Utils.java:13)
	at com.evokly.kafka.connect.mqtt.MqttSourceTask.messageArrived(MqttSourceTask.java:216)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:354)
	at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:162)
	... 1 more

**Comment by moperacz** [comment]
It seems that you haven't configured connector correctly. I will write some sample on the weekend how to do that.

**Comment by hjespers** [comment]
An example working connect-standalone.properties file would be helpful. I'm just working from what I believe to be the default settings.

**Comment by moperacz** [comment]
I've checked it some more over the weekend, and there are some things which 0.10 API defines (e.g., config() method) so in a couple of days I will release a new version (with some examples).

**Comment by moperacz** [comment]
@hjespers if you are interested in WIP, take a look on #11

**Comment by srijiths** [comment]
Same problem with Confluvent Kafka Version 0.10.0.0-cp1

**Comment by moperacz** [comment]
@srijiths did u try kafka_10 branch?

**Comment by srijiths** [comment]
Debugd your code and there is a null pointer exception here

mMessageProcessorClassName = props.get(MqttSourceConstant.MESSAGE_PROCESSOR);

[2016-07-04 13:31:36,088] INFO Class Name :null (com.evokly.kafka.connect.mqtt.MqttSourceConnector:214)

**Comment by srijiths** [comment]
@moperacz using master i was able to connect to MQTT and subscribe to a topic.
```
 Start a MqttSourceTask (com.evokly.kafka.connect.mqtt.MqttSourceConnector:65)
[2016-07-04 13:31:23,482] INFO Created connector mqtt (org.apache.kafka.connect.cli.ConnectStandalone:91)
[2016-07-04 13:31:23,486] INFO class for processing messages: null (com.evokly.kafka.connect.mqtt.MqttSourceConnector:75)
[2016-07-04 13:31:23,811] INFO [paho2864913584850244] Connected to Broker (com.evokly.kafka.connect.mqtt.MqttSourceConnector:124)
[2016-07-04 13:31:23,957] INFO [paho2864913584850244] Subscribe to 'test1' with QoS '1' (com.evokly.kafka.connect.mqtt.MqttSourceConnector:136)
```
But with kafka_10 branch i am not able to connect to MQTT with the same settings as before.
```
[2016-07-04 13:55:50,738] ERROR [paho2866380805822051] Connection to Broker failed! (com.evokly.kafka.connect.mqtt.MqttSourceConnector:119)
Unable to connect to server (32103) - java.net.ConnectException: Connection refused
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:79)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:590)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:70)
        ... 2 more
[2016-07-04 13:55:50,747] ERROR [paho2866380805822051] Subscribe failed!  (com.evokly.kafka.connect.mqtt.MqttSourceConnector:132)
Client is not connected (32104)
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:143)
        at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:721)
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:320)
        at org.eclipse.paho.client.mqttv3.MqttClient.subscribe(MqttClient.java:313)
        at com.evokly.kafka.connect.mqtt.MqttSourceTask.start(MqttSourceTask.java:127)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:137)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by srijiths** [comment]
@moperacz the issue was due to connecting to tcp://localhost:1883. A new issue created #17

**Comment by hjespers** [comment]
I have the latest kafka_10 code branch working with Confluent Platform 3.0 (aka Kafka 0.10). This is great work, thank you for contributing it. The connector is visible inside of Confluent Control Center and I can change all the configuration parameters via  Control Center GUI instead of via specifying them in the properties file. The data seems to be Base64 encoded when I get it back out using kafkacat or kafka-console-consumer.  There may be some enhancements possible to the way the data is encoded and decodes so users could configure at runtime if they want to use AVRO or any other schema for the messages.

**Comment by moperacz** [comment]
@hjespers good to hear that it is working.

as for base64 (i know, documentation/manuals):

The default "processor" is dummy one, and basically, it set schema to topic->string, body->bytes (https://github.com/evokly/kafka-connect-mqtt/blob/kafka_10/src/main/java/com/evokly/kafka/connect/mqtt/sample/DumbProcessor.java#L33), so it depends on your Kafka Connect configuration
if you change `key.converter` from JSON to `io.confluent.connect.avro.AvroConverter` Kafka Connect encodes the "base64" to Avro binary data.

we are using Avro with schema registry and its working excellent


The general idea is that you can provide `message_processor_class` (needs to implement `com.evokly.kafka.connect.mqtt.MqttMessageProcessor` interface) that receives binary (messages) data from MQTT (e.g. Google Protobuf stuff) and "process" it according to "some" iternal rules.

docs 😭

**Comment by hjespers** [comment]
I changed the connect properties file to include the following and it works like a charm. Thanks. Looking forward to the documentation ;-)

key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081

**Comment by srijiths** [comment]
@moperacz In kafka_10 branch , its working. Thank You

**Comment by hjespers** [comment]
I'm getting 20,000 msg/sec throughput (QoS 0) and 7,800 msg/sec throughput (QoS 1) with a single connector and everything running on my Macbook. This is awesome! Thanks again for making this. I'm streaming my connected car telemetry through it and (soon) into Kafka Streams for analytics.
