### ISSUE TITLE
ERROR Stopping after connector error

### ISSUE THREAD

**Issue by balag1986** [evokly/kafka-connect-mqtt#20]
Starting the apache kafka connect mqtt ended up with following error.

[2016-08-18 23:47:27,819] INFO Creating connector mqtt of type com.evokly.kafka.connect.mqtt.MqttSourceConnector (org.apache.kafka.connect.runtime.Worker:170)
[2016-08-18 23:47:27,820] INFO Instantiated connector mqtt with version 1.0-SNAPSHOT of type com.evokly.kafka.connect.mqtt.MqttSourceConnector (org.apache.kafka.connect.runtime.Worker:183)
[2016-08-18 23:47:27,821] INFO Start a MqttSourceConnector (com.evokly.kafka.connect.mqtt.MqttSourceConnector:50)
[2016-08-18 23:47:27,822] ERROR Stopping after connector error (org.apache.kafka.connect.cli.ConnectStandalone:91)
java.lang.NoClassDefFoundError: org/apache/kafka/common/config/ConfigDef$Recommender
        at com.evokly.kafka.connect.mqtt.MqttSourceConnector.start(MqttSourceConnector.java:52)
        at org.apache.kafka.connect.runtime.Worker.addConnector(Worker.java:186)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.startConnector(StandaloneHerder.java:197)
        at org.apache.kafka.connect.runtime.standalone.StandaloneHerder.putConnectorConfig(StandaloneHerder.java:145)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:85)
Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.config.ConfigDef$Recommender
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 5 more
[2016-08-18 23:47:27,826] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:68)
[2016-08-18 23:47:27,830] INFO Stopped ServerConnector@3f22168b{HTTP/1.1}{0.0.0.0:8083} (org.eclipse.jetty.server.ServerConnector:306)
[2016-08-18 23:47:27,835] INFO Stopped o.e.j.s.ServletContextHandler@23fb172e{/,null,UNAVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:865)
[2016-08-18 23:47:27,836] INFO Herder stopping (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:62)
[2016-08-18 23:47:27,837] INFO Herder stopped (org.apache.kafka.connect.runtime.standalone.StandaloneHerder:77)
[2016-08-18 23:47:27,837] INFO Worker stopping (org.apache.kafka.connect.runtime.Worker:115)
[2016-08-18 23:47:27,837] INFO Stopped FileOffsetBackingStore (org.apache.kafka.connect.storage.FileOffsetBackingStore:61)
[2016-08-18 23:47:27,837] INFO Worker stopped (org.apache.kafka.connect.runtime.Worker:155)
[2016-08-18 23:47:27,837] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:74)

Please help

**Comment by moperacz** [comment]
which version of kafka-connect do you use?
it seems that `org/apache/kafka/common/config/ConfigDef$Recommender` is not found...

try with kafka 0.10

**Comment by balag1986** [comment]
thanks! i am using kafka_2.11-0.9.0.1, let me try with kafka 0.10 and let you know how it goes

**Comment by balag1986** [comment]
it worked well with kafka 0.10, however the messages i publish from mqtt on a topic is received as byte arrays on kafka consumer.

**Comment by moperacz** [comment]
look at https://github.com/evokly/kafka-connect-mqtt/blob/master/src/main/java/com/evokly/kafka/connect/mqtt/sample/DumbProcessor.java

you can create your processor which implements `MqttMessageProcessor` interface and point your .properties to make use of your processor (we are doing this in-house)
